### ISSUE TITLE
请教个问题，apk 是怎么打包出来的😃

### ISSUE THREAD

**Issue by learner1999** [normalHamal/ygcp#1]
好像是用了个 webview？手动写了一个 Android 项目还是自动化的？

**Comment by normalHamal** [comment]
@learner1999  这个是h5打包的app，就是加了个webview而已，用的是wex5打包生成的

**Comment by learner1999** [comment]
@normalHamal 哦哦 ，是这样啊！

**Comment by normalHamal** [comment]
@learner1999 对滴，还没开始接触原生安卓，只能这样来了
